name: check code style

on: [push, pull_request]

permissions:
    contents: read
    pull-requests: read

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Check commit message
              uses: ./
              env:
                ACTIONS_STEP_DEBUG: ${{ vars.ACTIONS_STEP_DEBUG}}
              with:
                github-token: ${{ github.token }}
                scope-values: 'scope1,scope2'
